# Generated by Django 4.1.2 on 2022-11-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.CharField(max_length=20),
        ),
    ]
